drop table if exists sys_user_3;
drop table if exists sys_user_4;
drop table if exists sys_role_5;
drop table if exists sys_role_6;
drop table if exists sys_role_7;
drop table if exists sys_role_8;

drop table if exists sys_task_a;

create table sys_user_3 (
  user_id bigint generated by default as identity,
  username varchar(100),
  password varchar(100),
  salt varchar(100),
  primary key (user_id)
);
create table sys_user_4 (
  user_id bigint generated by default as identity,
  username varchar(100),
  password varchar(100),
  salt varchar(100),
  primary key (user_id)
);
create table sys_role_5 (
  role_id bigint generated by default as identity,
  user_id bigint,
  role_name varchar(100),
  primary key (role_id)
);
create table sys_role_6 (
  role_id bigint generated by default as identity,
  user_id bigint,
  role_name varchar(100),
  primary key (role_id)
);
create table sys_role_7 (
  role_id bigint generated by default as identity,
  user_id bigint,
  role_name varchar(100),
  primary key (role_id)
);
create table sys_role_8 (
  role_id bigint generated by default as identity,
  user_id bigint,
  role_name varchar(100),
  primary key (role_id)
);
create table sys_task_a (
  task_id bigint generated by default as identity,
  user_id bigint,
  task_name varchar(100),
  primary key (task_id)
);